config/routes.rb
Rails.application.routes.draw do
  resources :locacoes
  resources :enderecos
  resources :clientes
  resources :midias
  resources :filmes
  resources :categorias
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cliente.rb
class Cliente < ApplicationRecord
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nome, :telefone, :celular, :email)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_for @cliente, :html => { :class => "form-horizontal cliente" } do |f| %>

  <% if @cliente.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @cliente.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nome) %>
  </div>
  <div class="form-group">
    <%= f.label :telefone, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :telefone, :class => 'form-control' %>
    </div>
    <%=f.error_span(:telefone) %>
  </div>
  <div class="form-group">
    <%= f.label :celular, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :celular, :class => 'form-control' %>
    </div>
    <%=f.error_span(:celular) %>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                clientes_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/clientes/edit.html.erb
<%- model_class = Cliente -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/clientes/index.html.erb
<%- model_class = Cliente -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:telefone) %></th>
      <th><%= model_class.human_attribute_name(:celular) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= link_to cliente.id, cliente_path(cliente) %></td>
        <td><%= cliente.nome %></td>
        <td><%= cliente.telefone %></td>
        <td><%= cliente.celular %></td>
        <td><%= cliente.email %></td>
        <td><%=l cliente.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_cliente_path(cliente), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cliente_path(cliente),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_cliente_path,
            :class => 'btn btn-primary' %>

app/views/clientes/new.html.erb
<%- model_class = Cliente -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/clientes/show.html.erb
<%- model_class = Cliente -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @cliente.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:telefone) %>:</strong></dt>
  <dd><%= @cliente.telefone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:celular) %>:</strong></dt>
  <dd><%= @cliente.celular %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @cliente.email %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              clientes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_cliente_path(@cliente), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              cliente_path(@cliente),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>