config/routes.rb
Rails.application.routes.draw do
  resources :locacoes
  resources :enderecos
  resources :clientes
  resources :midias
  resources :filmes
  resources :categorias
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/midia.rb
class Midia < ApplicationRecord
  belongs_to :filme
end

app/controllers/midias_controller.rb
class MidiasController < ApplicationController
  before_action :set_midia, only: [:show, :edit, :update, :destroy]

  # GET /midias
  # GET /midias.json
  def index
    @midias = Midia.all
  end

  # GET /midias/1
  # GET /midias/1.json
  def show
  end

  # GET /midias/new
  def new
    @midia = Midia.new
  end

  # GET /midias/1/edit
  def edit
  end

  # POST /midias
  # POST /midias.json
  def create
    @midia = Midia.new(midia_params)

    respond_to do |format|
      if @midia.save
        format.html { redirect_to @midia, notice: 'Midia was successfully created.' }
        format.json { render :show, status: :created, location: @midia }
      else
        format.html { render :new }
        format.json { render json: @midia.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /midias/1
  # PATCH/PUT /midias/1.json
  def update
    respond_to do |format|
      if @midia.update(midia_params)
        format.html { redirect_to @midia, notice: 'Midia was successfully updated.' }
        format.json { render :show, status: :ok, location: @midia }
      else
        format.html { render :edit }
        format.json { render json: @midia.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /midias/1
  # DELETE /midias/1.json
  def destroy
    @midia.destroy
    respond_to do |format|
      format.html { redirect_to midias_url, notice: 'Midia was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_midia
      @midia = Midia.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def midia_params
      params.require(:midia).permit(:filme_id, :inutilizada)
    end
end

app/helpers/midias_helper.rb
module MidiasHelper
end

app/views/midias/_form.html.erb
<%= form_for @midia, :html => { :class => "form-horizontal midia" } do |f| %>

  <% if @midia.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@midia.errors.count, "error") %> prohibited this midia from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @midia.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :filme_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :filme_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:filme_id) %>
  </div>
  <div class="form-group">
    <%= f.label :inutilizada, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :inutilizada, :class => 'form-control' %>
    </div>
    <%=f.error_span(:inutilizada) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                midias_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/midias/edit.html.erb
<%- model_class = Midia -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/midias/index.html.erb
<%- model_class = Midia -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:filme_id) %></th>
      <th><%= model_class.human_attribute_name(:inutilizada) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @midias.each do |midia| %>
      <tr>
        <td><%= link_to midia.id, midia_path(midia) %></td>
        <td><%= midia.filme_id %></td>
        <td><%= midia.inutilizada %></td>
        <td><%=l midia.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_midia_path(midia), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      midia_path(midia),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_midia_path,
            :class => 'btn btn-primary' %>

app/views/midias/new.html.erb
<%- model_class = Midia -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/midias/show.html.erb
<%- model_class = Midia -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:filme_id) %>:</strong></dt>
  <dd><%= @midia.filme_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:inutilizada) %>:</strong></dt>
  <dd><%= @midia.inutilizada %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              midias_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_midia_path(@midia), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              midia_path(@midia),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>