config/routes.rb
Rails.application.routes.draw do
  resources :locacoes
  resources :enderecos
  resources :clientes
  resources :midias
  resources :filmes
  resources :categorias
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :cliente
end

app/controllers/enderecos_controller.rb
class EnderecosController < ApplicationController
  before_action :set_endereco, only: [:show, :edit, :update, :destroy]

  # GET /enderecos
  # GET /enderecos.json
  def index
    @enderecos = Endereco.all
  end

  # GET /enderecos/1
  # GET /enderecos/1.json
  def show
  end

  # GET /enderecos/new
  def new
    @endereco = Endereco.new
  end

  # GET /enderecos/1/edit
  def edit
  end

  # POST /enderecos
  # POST /enderecos.json
  def create
    @endereco = Endereco.new(endereco_params)

    respond_to do |format|
      if @endereco.save
        format.html { redirect_to @endereco, notice: 'Endereco was successfully created.' }
        format.json { render :show, status: :created, location: @endereco }
      else
        format.html { render :new }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enderecos/1
  # PATCH/PUT /enderecos/1.json
  def update
    respond_to do |format|
      if @endereco.update(endereco_params)
        format.html { redirect_to @endereco, notice: 'Endereco was successfully updated.' }
        format.json { render :show, status: :ok, location: @endereco }
      else
        format.html { render :edit }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enderecos/1
  # DELETE /enderecos/1.json
  def destroy
    @endereco.destroy
    respond_to do |format|
      format.html { redirect_to enderecos_url, notice: 'Endereco was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endereco
      @endereco = Endereco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def endereco_params
      params.require(:endereco).permit(:rua, :bairro, :numero, :cidade, :estado, :cep, :complemento, :cliente_id)
    end
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/views/enderecos/_form.html.erb
<%= form_for @endereco, :html => { :class => "form-horizontal endereco" } do |f| %>

  <% if @endereco.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@endereco.errors.count, "error") %> prohibited this endereco from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @endereco.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :rua, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :rua, :class => 'form-control' %>
    </div>
    <%=f.error_span(:rua) %>
  </div>
  <div class="form-group">
    <%= f.label :bairro, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :bairro, :class => 'form-control' %>
    </div>
    <%=f.error_span(:bairro) %>
  </div>
  <div class="form-group">
    <%= f.label :numero, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :numero, :class => 'form-control' %>
    </div>
    <%=f.error_span(:numero) %>
  </div>
  <div class="form-group">
    <%= f.label :cidade, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :cidade, :class => 'form-control' %>
    </div>
    <%=f.error_span(:cidade) %>
  </div>
  <div class="form-group">
    <%= f.label :estado, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :estado, :class => 'form-control' %>
    </div>
    <%=f.error_span(:estado) %>
  </div>
  <div class="form-group">
    <%= f.label :cep, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :cep, :class => 'form-control' %>
    </div>
    <%=f.error_span(:cep) %>
  </div>
  <div class="form-group">
    <%= f.label :complemento, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :complemento, :class => 'form-control' %>
    </div>
    <%=f.error_span(:complemento) %>
  </div>
  <div class="form-group">
    <%= f.label :cliente_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :cliente_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:cliente_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                enderecos_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/enderecos/edit.html.erb
<%- model_class = Endereco -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/enderecos/index.html.erb
<%- model_class = Endereco -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:rua) %></th>
      <th><%= model_class.human_attribute_name(:bairro) %></th>
      <th><%= model_class.human_attribute_name(:numero) %></th>
      <th><%= model_class.human_attribute_name(:cidade) %></th>
      <th><%= model_class.human_attribute_name(:estado) %></th>
      <th><%= model_class.human_attribute_name(:cep) %></th>
      <th><%= model_class.human_attribute_name(:complemento) %></th>
      <th><%= model_class.human_attribute_name(:cliente_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @enderecos.each do |endereco| %>
      <tr>
        <td><%= link_to endereco.id, endereco_path(endereco) %></td>
        <td><%= endereco.rua %></td>
        <td><%= endereco.bairro %></td>
        <td><%= endereco.numero %></td>
        <td><%= endereco.cidade %></td>
        <td><%= endereco.estado %></td>
        <td><%= endereco.cep %></td>
        <td><%= endereco.complemento %></td>
        <td><%= endereco.cliente_id %></td>
        <td><%=l endereco.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_endereco_path(endereco), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      endereco_path(endereco),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_endereco_path,
            :class => 'btn btn-primary' %>

app/views/enderecos/new.html.erb
<%- model_class = Endereco -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/enderecos/show.html.erb
<%- model_class = Endereco -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:rua) %>:</strong></dt>
  <dd><%= @endereco.rua %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bairro) %>:</strong></dt>
  <dd><%= @endereco.bairro %></dd>
  <dt><strong><%= model_class.human_attribute_name(:numero) %>:</strong></dt>
  <dd><%= @endereco.numero %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cidade) %>:</strong></dt>
  <dd><%= @endereco.cidade %></dd>
  <dt><strong><%= model_class.human_attribute_name(:estado) %>:</strong></dt>
  <dd><%= @endereco.estado %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cep) %>:</strong></dt>
  <dd><%= @endereco.cep %></dd>
  <dt><strong><%= model_class.human_attribute_name(:complemento) %>:</strong></dt>
  <dd><%= @endereco.complemento %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cliente_id) %>:</strong></dt>
  <dd><%= @endereco.cliente_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              enderecos_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_endereco_path(@endereco), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              endereco_path(@endereco),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>